### `r .$name`

A total of **`r sum(.$bpn@enrichr@num_sig_up_enrichr, .$bpn@enrichr@num_sig_down_enrichr)`** significantly altered pathways were identified in treatment groups compared to control groups (adjusted p-value <= 0.05) in the Top `r names(.$bpn@enrichr@threshold_up)` and Bottom `r names(.$bpn@enrichr@threshold_down)` of DEGs (**N = `r .$bpn@enrichr@num_upreg` & `r .$bpn@enrichr@num_downreg`, resp.**) by log2FoldChange (**>`r .$bpn@enrichr@threshold_up` or `r .$bpn@enrichr@threshold_down`< **) using **EnrichR**. Of which, we identified **`r .$bpn@enrichr@num_sig_up_enrichr`** up-regulated pathways & **`r .$bpn@enrichr@num_sig_down_enrichr`** down-regulated pathways.

* Number of significantly altered pathways (padj <= 0.05): **`r sum(.$bpn@enrichr@num_sig_up_enrichr, .$bpn@enrichr@num_sig_down_enrichr)`**
* Number of significantly up-regulated pathways: **`r .$bpn@enrichr@num_sig_up_enrichr`**
* Number of significantly down-regulated pathways: **`r .$bpn@enrichr@num_sig_down_enrichr`**

```{r}
.$bpn@enrichr@sig_up_enrichr %>% 
  format_enrichr_pathways %>%
  make_table(caption = paste(.$name, "Up-Regulated Pathways")) %>%
  DT::formatStyle("Term","white-space"="nowrap")

.$bpn@enrichr@sig_down_enrichr %>%
  format_enrichr_pathways %>%
  make_table(caption = paste(.$name, "Down-Regulated Pathways")) %>%
  DT::formatStyle("Term","white-space"="nowrap")
```