### `r .$name`

A total of **`r sum(.$bpn@gsea@num_sig_pos_enriched, .$bpn@gsea@num_sig_neg_enriched)`** significantly altered pathways were identified in treatment groups compared to control groups (adjusted p-value <= 0.05) on DEG (**n = `r nrow(.$data)`**), using Gene Set Enrichment Analysis, **GSEA**. Of which, we identified **`r .$bpn@gsea@num_sig_pos_enriched`** up-regulated pathways & **`r .$bpn@gsea@num_sig_neg_enriched`** down-regulated pathways.

* Number of pathways tested: **`r .$bpn@gsea@num_tested `**
* Number of significantly altered pathways (padj <= 0.05): **`r sum(.$bpn@gsea@num_sig_pos_enriched,.$bpn@gsea@num_sig_neg_enriched)`**
* Number of significantly up-regulated pathways: **`r .$bpn@gsea@num_sig_pos_enriched`**
* Number of significantly down-regulated pathways: **`r .$bpn@gsea@num_sig_neg_enriched`**

```{r}
.$bpn@gsea@sig_pos_enriched %>% 
  format_gsea_pathways() %>%
  make_table(caption = paste(.$name, "Up-regulated Pathways")) %>%
  DT::formatStyle("Term", "white-space" = "nowrap")

.$bpn@gsea@sig_neg_enriched %>%
  format_gsea_pathways() %>%
  make_table(caption = paste(.$name, "Down-regulated Pathways")) %>%
  DT::formatStyle("Term", "white-space" = "nowrap")
```