# For instructions on configuring the report see the README
species: mouse # [human, rat, mouse]
# gmt: Human_GOALL_with_GO_iea_March_01_2025_symbol.gmt # [Human, Rat, Mouse]
gmt: Mouse_GOALL_with_GO_iea_March_01_2025_symbol.gmt
data:
  - group1: 1 month WT
    group2: 3 month WT
    file: wt_1m-3m_clean.csv
  - group1: 1 month ProNGF
    group2: 3 month ProNGF
    file: pngf_1m-3m_clean.csv
  - group1: 3 month WT
    group2: 12 month WT
    file: wt_3m-12m_clean.csv
  - group1: 3 month ProNGF
    group2: 12 month ProNGF
    file: pngf_3m-12m_clean.csv
  - group1: 1 month WT
    group2: 12 month WT
    file: wt_1m-12m_clean.csv
  - group1: 1 month ProNGF
    group2: 12 month ProNGF
    file: pngf_1m-12m_clean.csv
design: design.csv

# Debugging
save_environment: true # Save whole environment or just global state?

# External assets - don't touch
humanmap: HGNChelper_currentHumanMap_2025-03-01.csv
hgnc: hgnc_complete_set_2025-03-01.csv
rgd: GENES_RAT_2025-03-01.csv
mgi: MRK_List2_2025-03-01.csv
lincs_fda: LINCS_FDA_Phases_2023-05-05.csv
embeddings: anc2vec_02_06_25_embeddings.rds
term2name: anc2vec_02_06_25_term2name.rds
